### ISSUE TITLE
Fehlermeldung beim Start

### ISSUE THREAD

**Issue by CKMartens** [arteck/iobroker.fullybrowser#7]
Ich habe meinen Server neu aufgesetzt. Er läuft nun mit Ubuntu 18.04 LTS, Nodejs V8.15.0

Nachdem ich von Github den Adapter geladen habe kam im Log diese Fehlermeldung:
```
fullybrowser.0 | 2018-12-29 14:40:19.057 | error | at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
-- | -- | -- | --
fullybrowser.0 | 2018-12-29 14:40:19.057 | error | at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
fullybrowser.0 | 2018-12-29 14:40:19.057 | error | at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:244:12)
fullybrowser.0 | 2018-12-29 14:40:19.057 | error | at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:319:9)
fullybrowser.0 | 2018-12-29 14:40:19.057 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:787:25)
fullybrowser.0 | 2018-12-29 14:40:19.057 | error | at createInstancesObjects (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:748:13)
fullybrowser.0 | 2018-12-29 14:40:19.057 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:788:29
fullybrowser.0 | 2018-12-29 14:40:19.057 | error | at initAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4989:62)
fullybrowser.0 | 2018-12-29 14:40:19.057 | error | at Object.ready (/opt/iobroker/node_modules/iobroker.fullybrowser/main.js:31:9)
fullybrowser.0 | 2018-12-29 14:40:19.057 | error | at main (/opt/iobroker/node_modules/iobroker.fullybrowser/main.js:435:33)
fullybrowser.0 | 2018-12-29 14:40:19.057 | error | TypeError: Cannot read property 'length' of undefined
fullybrowser.0 | 2018-12-29 14:40:19.056 | error | uncaught exception: Cannot read property 'length' of undefined
```
Der Adapter an sich scheint zu laufen, es kommen Daten von FullyBwowser, alle Datenpunkte sind angelegt und werden aktualisiert.

**Comment by arteck** [comment]
da waren noch keine ipadressen eingetragen

**Comment by CKMartens** [comment]
Ah, ok....

Danke
